#!/user/bin/env bash
spawn_glava () {
   res=$1
   kill $(ps -ax | grep glava | grep -v grep | awk '{print $1}') || true
   if [[ $res -eq 1920 ]]; then
      glava -e rc-graph.glsl -m graph -r 'setgeometry 0 780 1920 300' & disown
      glava -e rc-radial.glsl -m radial -r 'setgeometry 1670 480 500 520' & disown
   else
      glava -e rc-graph.glsl -m graph -r 'setgeometry 0 1855 3840 300' & disown
   fi
}

profile=$AUTORANDR_CURRENT_PROFILE
dir=$AUTORANDR_PROFILE_FOLDER

#(sleep 1 && xmonad --restart)&
case "$profile" in
    rv-laptop)
        sed -i 's/size: .*$/size: 10/' ~/.config/alacritty/alacritty.yml
        dconf write /org/gnome/desktop/interface/text-scaling-factor 1.0
        spawn_glava 1920
        ;;
    rv-dual)
        sed -i 's/size: .*$/size: 12/' ~/.config/alacritty/alacritty.yml
        dconf write /org/gnome/desktop/interface/text-scaling-factor 1.2
        spawn_glava 3840
        ;;
    nv-laptop)
        sed -i 's/size: .*$/size: 10/' ~/.config/alacritty/alacritty.yml
        dconf write /org/gnome/desktop/interface/text-scaling-factor 1.0
        #nvidia-settings --assign CurrentMetaMode="nvidia-auto-select +0+0 {ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}"
        spawn_glava 1920
        ;;
    nv-dual)
        sed -i 's/size: .*$/size: 12/' ~/.config/alacritty/alacritty.yml
        dconf write /org/gnome/desktop/interface/text-scaling-factor 1.2
        #nvidia-settings --assign CurrentMetaMode="DP-1: nvidia-auto-select +1920+0 {ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}, DP-2: nvidia-auto-select +0+1080 {ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}"
        spawn_glava 3840
        ;;
esac
