#!/usr/bin/env bash
output=$1
dir="$(dirname "$output")"
fn="$(basename "$output")"
nix-shell ./shell.nix --command 'cabal install exe:xmonadwm --enable-executable-stripping --enable-optimization=2 --installdir=$dir --overwrite-policy=always'
ln -sf $dir/xmonadwm  "$output"