resolver: lts-19.21
packages:
  - .

extra-deps:
  - xmobar-0.44.1@sha256:fac935348768052c29f6d2f81962d9f8b2974843298f6fd8cb839cd1094f089e,14778
  #- git: https://github.com/Ongy/netlink-hs.git
  #   commit: b0f3ab9a4766a3da7b26991e404695154ee74556
  # - git: https://codeberg.org/xmobar/xmobar.git
  #   commit: ba24c0b31c2b0c5806909f3c982802a3b11c7586
  # - git: https://codeberg.org/jao/xmobar-config.git
  #   commit: 07c093c9b351466e60b93692c7d05b949bd71b0c

# flags:
#   xmobar:
#     all_extensions: true
    # with_dbus: true
    # with_xft: true
    # with_mpd: true
    # with_rtsopts: true
    # with_mpris: true
    # with_inotify: true
    # with_nl80211: true
    # with_alsa: true
    # #with_xpm: true
    # with_weather: true
flags:
  xmobar:
    all_extensions: true


nix:
  enable: true
  packages:
    - gcc
    - pkgconfig
    - xorg.libX11.dev
    - xorg.libX11
    - xlibsWrapper
    - xorg.libXext
    - xorg.libXinerama
    - xorg.libXrandr
    - xorg.libXrender
    - xorg.libXft
    - xorg.libXrandr
    - xorg.libXScrnSaver
    - alsa-lib.dev
    - haskellPackages.xmobar
    - xorg.libXpm
    - wirelesstools
